version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: 
          name: Update NPM
          command: sudo npm i -g npm
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Install Assert NPM Package
          command: npm i assert --save-dev
      - run: 
          name: Install Spectron NPM Package
          command: npm i spectron --save-dev
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: sudo npm install electron-packager -g
      - run: sudo npm install electron-installer-debian -g
  linuxApp:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run:
          name: Package app for linux
          command: electron-packager . OutFlux --overwrite --platform=linux --arch=x64 --ignore=node_modules/.bin
      - run:
          name: test linux app
          command: npm test

workflows:
  version: 2
  linuxTest:
    jobs:
      - build
      - linuxApp
        requires:
          - build
          

